name: 'GitHub Assets to S3'
description: 'Transfers GitHub release assets to a S3 bucket.'
author: 'okcodes'

branding:
  icon: 'upload-cloud'
  color: 'yellow'

inputs:
  endpoint:
    description: The endpoint URL for the S3 or S3-compatible storage service, e.g., "https://s3.us-east-000.backblazeb2.com".
    required: true
  region:
    description: The region where your S3 bucket or S3-compatible storage service is located, e.g., "us-east-000".
    required: true
  accessKeyId:
    description: The access key ID for authenticating with the S3 or S3-compatible storage service.
    required: true
  secretAccessKey:
    description: The secret access key for authenticating with the S3 or S3-compatible storage service.
    required: true
  bucket:
    description: The name of the bucket in the S3 or S3-compatible storage service where release assets will be uploaded.
    required: true
  folder:
    description: Folder in S3 where to store the release assets. If not set, the assets will be stored in the root folder of the bucket.
    required: false
    default: ''
  urlTemplate:
    description: Template to build the assets URL on S3. It will interpolate "{OBJECT_KEY}" with the object name of each asset once in S3, e.g., "https://bucket-name.s3.amazonaws.com/{OBJECT_KEY}". The bucket can be private or public.
    required: true
  repository:
    description: The GitHub repository name in the format 'owner/repo' from which release assets will be uploaded.
    required: true
  releaseId:
    description: The ID of the release from where the assets will be uploaded. Only one, either "releaseId" or "releaseTag" must be provided, if both are provided, or none, the action will fail.
    required: false
  releaseTag:
    description: The tag name of the release from which assets will be uploaded. Only one, either "releaseId" or "releaseTag" must be provided, if both are provided, or none, the action will fail.
    required: false
  githubToken:
    description: A GitHub token with permissions to access private repositories if the repository is private. This token is used to authenticate requests for downloading release assets.
    required: true

runs:
  using: node20
  main: dist/index.js
