name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: 'write'

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Transfer Assets From Published Release
        uses: ./
        with:
          endpoint: ${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          accessKeyId: ${{ secrets.S3_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.S3_BUCKET }}
          repository: ${{ github.repository }}
          releaseTag: e2e-published-release
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          s3UrlTemplate: https://{BUCKET}.s3.{REGION}.backblazeb2.com/{FILENAME}

      - name: Test Transfer Assets From Draft Release
        uses: ./
        with:
          endpoint: ${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          accessKeyId: ${{ secrets.S3_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.S3_BUCKET }}
          repository: ${{ github.repository }}
          releaseTag: e2e-draft-release
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          s3UrlTemplate: https://{BUCKET}.s3.{REGION}.backblazeb2.com/{FILENAME}
